### ISSUE TITLE
Page loading error

### ISSUE THREAD

**Issue by wz1616** [transitive-bullshit/nextjs-notion-starter-kit#100]
Page loading error when the title of the Notion page contains English

Issue page link https://www.yizhen.ga/wearos

![image](https://user-images.githubusercontent.com/62297116/115721035-36915d80-a3b0-11eb-85ae-d7cf17826839.png)
![image](https://user-images.githubusercontent.com/62297116/115720894-0f3a9080-a3b0-11eb-999b-a61fe769ac04.png)

**Comment by transitive-bullshit** [comment]
Hey @wz1616, what did the issue end up being?

**Comment by wz1616** [comment]
> Hey @wz1616, what did the issue end up being?

Ah, I found the problem, because I put an unpublished page on the blog root page, as if all pages with English titles would be jumped to this unpublished page. It's normal to delete that unpublished page. 
I have worked it out!
Here is the Vercel log:

} Error: Notion page not found "c2a1f2ee2c7e4b3ba0a910175c648d3d"
21:34:56  
    at NotionAPI.<anonymous> (/vercel/path1/node_modules/notion-client/build/cjs/notion-api.js:82:35)
21:34:56  
    at step (/vercel/path1/node_modules/notion-client/build/cjs/notion-api.js:44:23)
21:34:56  
    at Object.next (/vercel/path1/node_modules/notion-client/build/cjs/notion-api.js:25:53)
21:34:56  
    at fulfilled (/vercel/path1/node_modules/notion-client/build/cjs/notion-api.js:16:58)
21:34:56  
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
21:34:56  
site build error 0 {
