### ISSUE TITLE
Error loading page

### ISSUE THREAD

**Issue by chiperman** [transitive-bullshit/nextjs-notion-starter-kit#244]
I have forked the newest repo and deployed on the Vercel successfully, but I can only visit the homepage of my blog : https://notion.chiperman.tk, if I click the detail page of any link, it shows an error loading page. You can visite my repo: www.github.com/chiperman/nextjs-notion-starter-kit

The error from the Chrome console when I visit pages such as https://notion.chiperman.tk/game-gallery.
```
Failed to load resource: the server responded with a status of 504 ()
GET https://notion.chiperman.tk/_next/data/MveCnhFeQWwn6tq4BV89J/game-gallery.json 504
main-38102973b285480e.js:1 Error: Failed to load static props at main-38102973b285480e.js:1:51922
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Uncaught (in promise) Error: Failed to load static props at main-38102973b285480e.js:1:51922
```

This is the log of my Vercel when deploying.
```
NotionAPI collectionQuery error Response code 400 (Bad Request)
--
22:16:51.805 | HTTPError: Response code 400 (Bad Request)
22:16:51.805 | at Request.<anonymous> (/vercel/path0/.next/server/chunks/228.js:738:42)
22:16:51.805 | at runMicrotasks (<anonymous>)
22:16:51.805 | at processTicksAndRejections (internal/process/task_queues.js:95:5) {
22:16:51.805 | code: undefined,
22:16:51.805 | timings: {
22:16:51.805 | start: 1648477011626,
22:16:51.805 | socket: 1648477011626,
22:16:51.805 | lookup: 1648477011626,
22:16:51.805 | connect: 1648477011638,
22:16:51.806 | secureConnect: 1648477011653,
22:16:51.806 | upload: 1648477011653,
22:16:51.806 | response: 1648477011803,
22:16:51.806 | end: 1648477011803,
22:16:51.806 | error: undefined,
22:16:51.806 | abort: undefined,
22:16:51.806 | phases: {
22:16:51.806 | wait: 0,
22:16:51.806 | dns: 0,
22:16:51.806 | tcp: 12,
22:16:51.806 | tls: 15,
22:16:51.806 | request: 0,
22:16:51.806 | firstByte: 150,
22:16:51.806 | download: 0,
22:16:51.806 | total: 177
22:16:51.806 | }
22:16:51.806 | }
22:16:51.806 | }
```

**Comment by transitive-bullshit** [comment]
Hmmmm, I think this may have to do with non-ascii characters in your page names.

Let me see if I can track down what's going on.

**Comment by transitive-bullshit** [comment]
I fixed one issue in `react-notion-x`, so if you update to latest that should help.

I think you have a lot of linked databases that are causing issues. My recommendation would be to remove any unreferenced collections, get it working, and then slowly add stuff back from there.

I'd also recommend that you set `includeNotionIdInUrls: false` in your site config.
