### ISSUE TITLE
It always takes 10 minutes when connecting vercel. Failure is then displayed

### ISSUE THREAD

**Issue by Hurtblack** [transitive-bullshit/nextjs-notion-starter-kit#266]
#### Description

```bash
[12:05:42.199] Cloning github.com/Hurtblack/nextjs-notion-starter-kit (Branch: main, Commit: 83c77cf)
[12:05:42.578] Cloning completed: 379.333ms
[12:05:42.940] Installing build runtime...
[12:05:46.960] Build runtime installed: 4.019s
[12:05:47.690] Looking up build cache...
[12:05:47.951] Build Cache not found
[12:05:48.153] Warning: Due to "engines": { "node": ">=14.17" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
[12:05:48.162] Installing dependencies...
[12:05:48.410] yarn install v1.22.17
[12:05:48.495] [1/5] Validating package.json...
[12:05:48.498] [2/5] Resolving packages...
[12:05:48.561] warning Resolution field "chrome-aws-lambda@6.0.0" is incompatible with requested version "chrome-aws-lambda@^10.1.0"
[12:05:48.562] warning Resolution field "puppeteer-core@6.0.0" is incompatible with requested version "puppeteer-core@^10.4.0"
[12:05:48.723] [3/5] Fetching packages...
[12:06:30.199] [4/5] Linking dependencies...
[12:06:30.202] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[12:06:30.202] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[12:06:30.203] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[12:06:30.204] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[12:06:30.208] warning "static-tweets > @vercel/fetch@6.2.0" has incorrect peer dependency "@types/node-fetch@^2.6.1".
[12:07:04.961] [5/5] Building fresh packages...
[12:07:06.089] Done in 77.68s.
[12:07:06.125] Detected Next.js version: 12.1.3
[12:07:06.127] Running "yarn run build"
[12:07:06.403] yarn run v1.22.17
[12:07:06.448] $ next build
[12:07:07.148] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[12:07:07.148] This information is used to shape Next.js' roadmap and prioritize features.
[12:07:07.149] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[12:07:07.149] https://nextjs.org/telemetry
[12:07:07.149] 
[12:07:07.188] info  - Checking validity of types...
[12:07:12.171] warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
[12:07:13.088] info  - Creating an optimized production build...
[12:07:36.864] info  - Compiled successfully
[12:07:36.864] info  - Collecting page data...
[12:07:38.208] getSiteMap 1/1 (100%) {
[12:07:38.208]   domain: 'https://ltyzqhh.notion.site/e34198b9092149fe8ccedf6c72e24bc8?v=14d48687ea28460294b818d52ee43818',
[12:07:38.209]   name: '内河大魔王',
[12:07:38.209]   rootNotionPageId: 'e34198b9092149fe8ccedf6c72e24bc8',
[12:07:38.209]   rootNotionSpaceId: 'd06b5e15-7998-4a2a-94ac-b2ba71411ae9',
[12:07:38.209]   description: '博客'
[12:07:38.209] }
```

Run for 1 minute here and then the card master, after which the deployment fails

#### Notion Test Page ID
https://ltyzqhh.notion.site/e34198b9092149fe8ccedf6c72e24bc8?v=14d48687ea28460294b818d52ee43818
rootNotionPageId: 'e34198b9092149fe8ccedf6c72e24bc8',
block.space_id:'d06b5e15-7998-4a2a-94ac-b2ba71411ae9'

**Comment by Zeeech** [comment]
Hello,Hurtblack How is this problem solved?

**Comment by Hurtblack** [comment]
> 
I didn't solve this problem, are you the same problem?

**Comment by Zeeech** [comment]
> 

yes,  collecting page data timeout


> Build error occurred
--
10:33:33.373 | Error: Collecting page data for /[pageId] is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout
10:33:33.373 | at onRestart (/vercel/path0/node_modules/next/dist/build/index.js:489:31)
10:33:33.373 | at Worker.isPageStatic (/vercel/path0/node_modules/next/dist/lib/worker.js:49:40)
10:33:33.373 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
10:33:33.374 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
10:33:33.374 | at async /vercel/path0/node_modules/next/dist/build/index.js:555:48
10:33:33.374 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
10:33:33.374 | at async Promise.all (index 1)
10:33:33.374 | at async /vercel/path0/node_modules/next/dist/build/index.js:536:13
10:33:33.374 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
10:33:33.374 | at async /vercel/path0/node_modules/next/dist/build/index.js:513:166
10:33:33.406 | error Command failed with exit code 1.
10:33:33.406 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:33:33.416 | Error: Command "yarn run build" exited with 1

**Comment by Hurtblack** [comment]
Wait for the author reply to see it XD，I still haven't figured out why it timed out

**Comment by transitive-bullshit** [comment]
Hmmm, the page it's erroring on is https://ltyzqhh.notion.site/Java-af8395f3ce234731806b0c76981cd718

Which means that one of your site pages is linking to another page in your workspace — which is then including all of the pages in your workspace.

This still should work, but it will be really inefficient. I'm looking into why this is failing for you now.

**Comment by transitive-bullshit** [comment]
This page: https://ltyzqhh.notion.site/Notion-c28504c2d118476d8a41f5020e49c0f2 links to https://ltyzqhh.notion.site/8ebb711165d44b1a9c357e352e1a6130, which then includes your entire workspace.

If you remove that link, then your site shrinks significantly and everything should work fine.

**Comment by transitive-bullshit** [comment]
Let me think about what I can do to try and make this type of error easier to catch.

**Comment by chancenju** [comment]
> 让我想想我可以做些什么来尝试让这种类型的错误更容易被发现。

please help us. I got the same issue. I deployed well on vercel, and it works for a month. But when i update an article today. It does not update any more today. I try to redeploye and get the same issue. show cant find page id

**Comment by transitive-bullshit** [comment]
@chancenju what is your root notion page ID so I can test?

**Comment by chancenju** [comment]
4023b3b0cf7248229f1e18b7e2c8d44e

**Comment by transitive-bullshit** [comment]
@chancenju have you merged the latest version of the starter kit?

I just tried locally and it seems to build fine using `4023b3b0cf7248229f1e18b7e2c8d44e` as the `rootNotionPageId`:

```
Page                                        Size     First Load JS
┌ ● / (ISR: 10 Seconds) (6639 ms)           512 B           168 kB
├   /_app                                   0 B             107 kB
├ ● /[pageId] (ISR: 10 Seconds) (92089 ms)  519 B           168 kB
├   ├ /表现层转移 (13023 ms)
├   ├ /战神测评 (9791 ms)
├   ├ /中科院物理所美国光物理学会学生分会 (8723 ms)
├   ├ /椭偏仪 (8126 ms)
├   ├ /陈鲲 (7555 ms)
├   ├ /appium控制手机app (7015 ms)
├   ├ /ah-溢价交易策略实战 (6873 ms)
├   └ [+6 more paths] (avg 4904 ms)
├ ○ /404 (550 ms)                           240 B           168 kB
├ λ /api/get-tweet-ast/[tweetId]            0 B             107 kB
├ λ /api/search-notion                      0 B             107 kB
├ λ /api/social-image                       0 B             107 kB
├ λ /robots.txt                             258 B           108 kB
└ λ /sitemap.xml                            262 B           108 kB
+ First Load JS shared by all               107 kB
  ├ chunks/framework-97f36a3cecebe63c.js    42 kB
  ├ chunks/main-f1cd301036dd87c7.js         28.2 kB
  ├ chunks/pages/_app-12d3c43f802fd332.js   34.7 kB
  ├ chunks/webpack-fdcf071a85dba1c6.js      2.44 kB
  └ css/b185f42233e1d741.css                18 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

✨  Done in 31.75s.
```

**Comment by chancenju** [comment]
> @chancenju what is your root notion page ID so I can test?
ha, I just thought why it works again. Thank you for that.

**Comment by chancenju** [comment]
I closed my VPN and it works. May be there is something wrong with my network. Anyway, thank you for helping

**Comment by Hurtblack** [comment]
> Let me think about what I can do to try and make this type of error easier to catch.

I deleted the page and it's now ready to deploy, but I still have a few questions to ask.Is it that I have too many pages? What can I do to avoid these problems, and should The About page and Context page also be under this workspace? I'm not able to add articles from other workspaces

**Comment by transitive-bullshit** [comment]
> Is it that I have too many pages?

I'm not sure. There was something in the other pages you're linking to that was causing the notion API to not respond. Sometimes if you are including hundreds or thousands of pages, when you really only mean to include a handful of pages for your site, then one of those pages ends up containing a private resource or something from another workspace, and that's where it can run into trouble.

> Should The About page and Context page also be under this workspace? I'm not able to add articles from other workspaces

Yes; ideally any pages on your site are all located under the same workspace — and ideally under the same root page within that workspace.
