### ISSUE TITLE
Linux unable to npm install nor yarn, dependancy not found or in error

### ISSUE THREAD

**Issue by JOduMonT** [transitive-bullshit/nextjs-notion-starter-kit#267]
I clone, then config, then run `npm install` and I ended here looking if I was alone.
I'm using
- Ubuntu 20.04LTS
- Node JS 16.14.2
- my NotionPage: https://www.notion.so/jodumont/JDuMonT-Consulting-d7f1b785ee854d2086bfbef6eec7669e

> Lots of dependency issues should be resolved in `react-notion-x` v6
```
jond@z170m:/srv/shares/Public/nextjs-notion-starter-kit$ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: next-api-og-image@2.2.1
npm WARN Found: peer puppeteer-core@"6.0.x" from chrome-aws-lambda@6.0.0
npm WARN node_modules/next-api-og-image/node_modules/chrome-aws-lambda
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer puppeteer-core@"6.0.x" from chrome-aws-lambda@6.0.0
npm WARN node_modules/next-api-og-image/node_modules/chrome-aws-lambda
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-notion-x@6.9.5
npm ERR! Found: katex@0.15.3
npm ERR! node_modules/katex
npm ERR!   katex@"^0.15.3" from the root project
npm ERR!   peer katex@">=0.9" from @matejmazur/react-katex@3.1.3
npm ERR!   node_modules/@matejmazur/react-katex
npm ERR!     @matejmazur/react-katex@"^3.1.3" from react-notion-x@6.9.5
npm ERR!     node_modules/react-notion-x
npm ERR!       react-notion-x@"^6.9.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional katex@"^0.13.18" from react-notion-x@6.9.5
npm ERR! node_modules/react-notion-x
npm ERR!   react-notion-x@"^6.9.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: katex@0.13.24
npm ERR! node_modules/katex
npm ERR!   peerOptional katex@"^0.13.18" from react-notion-x@6.9.5
npm ERR!   node_modules/react-notion-x
npm ERR!     react-notion-x@"^6.9.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/jond/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jond/.npm/_logs/2022-04-13T06_43_27_232Z-debug-0.log
```

even with `npm install --force` it is not working
```
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: next-api-og-image@2.2.1
npm WARN Found: peer puppeteer-core@"6.0.x" from chrome-aws-lambda@6.0.0
npm WARN node_modules/next-api-og-image/node_modules/chrome-aws-lambda
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer puppeteer-core@"6.0.x" from chrome-aws-lambda@6.0.0
npm WARN node_modules/next-api-og-image/node_modules/chrome-aws-lambda
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-notion-x@6.9.5
npm WARN Found: katex@0.15.3
npm WARN node_modules/katex
npm WARN   katex@"^0.15.3" from the root project
npm WARN   1 more (@matejmazur/react-katex)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional katex@"^0.13.18" from react-notion-x@6.9.5
npm WARN node_modules/react-notion-x
npm WARN   react-notion-x@"^6.9.5" from the root project
npm WARN 
npm WARN Conflicting peer dependency: katex@0.13.24
npm WARN node_modules/katex
npm WARN   peerOptional katex@"^0.13.18" from react-notion-x@6.9.5
npm WARN   node_modules/react-notion-x
npm WARN     react-notion-x@"^6.9.5" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
```

then I remove my repo and reclone it then run [yarn](url)
which didnt work also so I tried with `sudo yarn`
```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "chrome-aws-lambda@6.0.0" is incompatible with requested version "chrome-aws-lambda@^10.1.0"
warning Resolution field "puppeteer-core@6.0.0" is incompatible with requested version "puppeteer-core@^10.4.0"
warning Lockfile has incorrect entry for "@types/node-fetch@^2.6.1". Ignoring it.
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "static-tweets > @vercel/fetch@6.2.0" has incorrect peer dependency "@types/node-fetch@^2.6.1".
error An unexpected error occurred: "EACCES: permission denied, unlink '/srv/shares/Public/nextjs-notion-starter-kit/node_modules/.bin/acorn'".
info If you think this is a bug, please open a bug report with the information provided in "/srv/shares/Public/nextjs-notion-starter-kit/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
jond@z170m:/srv/shares/Public/nextjs-notion-starter-kit$ sudo yarn
yarn install v1.22.18
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "chrome-aws-lambda@6.0.0" is incompatible with requested version "chrome-aws-lambda@^10.1.0"
warning Resolution field "puppeteer-core@6.0.0" is incompatible with requested version "puppeteer-core@^10.4.0"
warning Lockfile has incorrect entry for "@types/node-fetch@^2.6.1". Ignoring it.
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "static-tweets > @vercel/fetch@6.2.0" has incorrect peer dependency "@types/node-fetch@^2.6.1".
[5/5] Building fresh packages...
error /srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp
Output:
sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-linux-x64.tar.br
/bin/sh: 1: prebuild-install: Permission denied
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
   24 | #include <vips/vips8>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.13.0-30-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
```

which remembered me why I hate nextjs and all these js stuff, AKA too much dependency

**Comment by JOduMonT** [comment]
now yarn dev run but

```
yarn run v1.22.18
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
event - compiled client and server successfully in 4.9s (809 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

wait  - compiling / (client and server)...
wait  - compiling...
event - compiled client and server successfully in 247 ms (830 modules)
(node:969047) [DEP0128] DeprecationWarning: Invalid 'main' field in '/srv/shares/Public/nextjs-notion-starter-kit/node_modules/@react-icons/all-files/package.json' of 'lib'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 156 ms (830 modules)
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
at resolveDispatcher (/srv/shares/Public/nextjs-notion-starter-kit/node_modules/react/cjs/react.development.js:1476:13)
at Object.useContext (/srv/shares/Public/nextjs-notion-starter-kit/node_modules/react/cjs/react.development.js:1484:20)
at Html (webpack-internal:///../../../../usr/lib/node_modules/next/dist/pages/_document.js:186:73)
at renderWithHooks (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
at renderIndeterminateComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
at renderContextProvider (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5710:3)
at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5807:11)
at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
at resolveDispatcher (/srv/shares/Public/nextjs-notion-starter-kit/node_modules/react/cjs/react.development.js:1476:13)
at Object.useContext (/srv/shares/Public/nextjs-notion-starter-kit/node_modules/react/cjs/react.development.js:1484:20)
at Html (webpack-internal:///../../../../usr/lib/node_modules/next/dist/pages/_document.js:186:73)
at renderWithHooks (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
at renderIndeterminateComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
at renderContextProvider (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5710:3)
at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5807:11)
at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
error - Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp/lib/constructor.js
- /srv/shares/Public/nextjs-notion-starter-kit/node_modules/sharp/lib/index.js
- /srv/shares/Public/nextjs-notion-starter-kit/node_modules/lqip-modern/index.js
- /srv/shares/Public/nextjs-notion-starter-kit/.next/server/pages/index.js
- /usr/lib/node_modules/next/dist/server/require.js
- /usr/lib/node_modules/next/dist/server/load-components.js
- /usr/lib/node_modules/next/dist/build/utils.js
- /usr/lib/node_modules/next/dist/build/output/store.js
- /usr/lib/node_modules/next/dist/build/output/index.js
- /usr/lib/node_modules/next/dist/cli/next-dev.js
- /usr/lib/node_modules/next/dist/bin/next

- Remove the "node_modules/sharp" directory then run
"npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
at resolveDispatcher (/srv/shares/Public/nextjs-notion-starter-kit/node_modules/react/cjs/react.development.js:1476:13)
at Object.useContext (/srv/shares/Public/nextjs-notion-starter-kit/node_modules/react/cjs/react.development.js:1484:20)
at Html (webpack-internal:///../../../../usr/lib/node_modules/next/dist/pages/_document.js:186:73)
at renderWithHooks (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
at renderIndeterminateComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
at renderContextProvider (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5710:3)
at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5807:11)
at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
at resolveDispatcher (/srv/shares/Public/nextjs-notion-starter-kit/node_modules/react/cjs/react.development.js:1476:13)
at Object.useContext (/srv/shares/Public/nextjs-notion-starter-kit/node_modules/react/cjs/react.development.js:1484:20)
at Html (webpack-internal:///../../../../usr/lib/node_modules/next/dist/pages/_document.js:186:73)
at renderWithHooks (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
at renderIndeterminateComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
at renderContextProvider (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5710:3)
at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5807:11)
at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)





```

**Comment by transitive-bullshit** [comment]
Hmmm, using `sudo` with yarn means you have some local issues with how your dev env is set up.

I would recommend looking into using `nvm` if you're not already.

For the `sharp` error, we're using it to generate LQIP preview images. So if you don't want this feature, then you can safely remove [sharp](https://github.com/lovell/sharp) and `lqip-modern` (as well as any places in the code it's used). Or check out the [sharp docs](https://github.com/lovell/sharp) for how to get it installed on Linux.

For the `Error: Invalid hook call` error you're seeing, it's honestly really hard to tell what's going on. It's difficult to reason about what might be happening in your local development environment.

Do you have any packages linked together using "yarn link" or "npm link"? The only times I really see that error are when I'm linking packages locally and don't have react + react-dom linked as well.

**Comment by JOduMonT** [comment]
So; I took the time to rebuild a plain VM
after reading your comment, I suspect my Ubuntu had too much history and exotic config.

### On Debian Testing it work like a charm

I installed **NodeJS Current** (not the LTS like I had on the Ubuntu)
````bash
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
````

#### and Yarn
````bash
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
````

then now after cloning, running `yarn` and `yarn dev`
everything work
