### ISSUE TITLE
Vercel social images not found, failing to generate

### ISSUE THREAD

**Issue by danthegoodman1** [transitive-bullshit/nextjs-notion-starter-kit#310]
#### Description

When running a local verison with `npm run dev`, I can see the opengraph images generated fine.

However when I build on Vercel, they are becoming not found: https://blog.danthegoodman.com/api/social-image?id=83b28450-5d46-4693-9291-0b6577bfb364

Full page https://blog.danthegoodman.com/insider-trading

#### Notion Test Page ID

83b28450-5d46-4693-9291-0b6577bfb364

I see the following function errors:

```
[GET] /api/social-image?id=83b28450-5d46-4693-9291-0b6577bfb364
19:33:14:17
2022-05-19T23:33:14.947Z	undefined	ERROR	(node:9) [DEP0128] DeprecationWarning: Invalid 'main' field in '/var/task/node_modules/@react-icons/all-files/package.json' of 'lib'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
2022-05-19T23:33:18.755Z	beda1e8f-2b74-4b6a-a78a-afd6cd19554e	ERROR	Error: Failed to launch the browser process!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:532:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-05-19T23:33:18.755Z	beda1e8f-2b74-4b6a-a78a-afd6cd19554e	ERROR	Error: Failed to launch the browser process!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:532:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
RequestId: beda1e8f-2b74-4b6a-a78a-afd6cd19554e Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by danthegoodman1** [comment]
I've also tried wiping the default lock files, and updates all packages as permitted by `yarn`

**Comment by danthegoodman1** [comment]
I've also engaged Vercel support as well on the matter

**Comment by danthegoodman1** [comment]
pinning the version in the `package.json` worked:

```
 "engines": {
    "node": "14.19.0"
  },
```

**Comment by transitive-bullshit** [comment]
Interesting; it seems that there's an issue between Vercel / AWS Lambda's recent addition of Node.js 16 support and `chrome-aws-lambda`.

Thanks for responding with the fix, as I'm sure others will also run into the same issue.

**Comment by quacrobat** [comment]
Hi, so are we saying to be able to use Social Images, we need to downgrade to Node 14 ? Any potential side-effects?
Thanks

**Comment by soumendrak** [comment]
This `14.19.0` version solution is not working anymore.

**Comment by transitive-bullshit** [comment]
I'm working on an update that uses https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation
