### ISSUE TITLE
Page Generation Fails on Certain Pages with 502 error

### ISSUE THREAD

**Issue by Lermatroid** [transitive-bullshit/nextjs-notion-starter-kit#335]
When generating the pages using `npm run build` pages time out after 2 attempts. This happens even after reattempting to build.

Page ID that errors: c7b8caef-97c8-4138-a85a-982dbe71cb29

**Comment by ccc159** [comment]
I also have this bug but every time when I build, one or two random pages will have this error.

```
Error occurred prerendering page "/troi". Read more: https://nextjs.org/docs/messages/prerender-error
HTTPError: Response code 502 (Bad Gateway)
    at Request.<anonymous> (C:\Users\jch\Desktop\nextjs-notion-starter-kit\node_modules\notion-client\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by ccc159** [comment]
@transitive-bullshit Could you help figure out what could be the issue here? The fact that it's random pages getting this error is not really debuggable.. thanks!
