### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by anudeepreddy** [transitive-bullshit/nextjs-notion-starter-kit#67]
Hey,

I was trying to build my blog this morning and it ends up with a build error. The dev command throws a 400 bad request error. This is the entire error messages that i can see in my console. I will be happy to provide you with more information if required.
```
{
  domain: 'notion-blog-eta-nine.vercel.app',
  name: 'Anudeep Reddy',
  rootNotionPageId: 'dd2a0cbdee2c46fb88de8d65fc47c308',
  rootNotionSpaceId: null,
  description: 'Example site description'
}
page error notion-blog-eta-nine.vercel.app HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/workspace/nextjs-notion-starter-kit/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1615095042241,
    socket: 1615095042242,
    lookup: 1615095042290,
    connect: 1615095042329,
    secureConnect: 1615095042340,
    upload: 1615095042340,
    response: 1615095042369,
    end: 1615095042371,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 48,
      tcp: 39,
      tls: 11,
      request: 0,
      firstByte: 29,
      download: 2,
      total: 130
    }
  }
}
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/workspace/nextjs-notion-starter-kit/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1615095042241,
    socket: 1615095042242,
    lookup: 1615095042290,
    connect: 1615095042329,
    secureConnect: 1615095042340,
    upload: 1615095042340,
    response: 1615095042369,
    end: 1615095042371,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 48,
      tcp: 39,
      tls: 11,
      request: 0,
      firstByte: 29,
      download: 2,
      total: 130
    }
  }
}
```

**Comment by emindeniz99** [comment]
Did you upgrade your npm packages up to master repo’s versions?
After that, dont forget ‘yarn install’.
I encountered with same issue yesterday. 

Notion has changed something at API, Travis fixed it at his repo’s

**Comment by anudeepreddy** [comment]
Thanks man. It works likes charm now✨

**Comment by transitive-bullshit** [comment]
Thanks @emindeniz99 🙏 Yep, notion made a breaking change to their API recently which was fixed in `react-notion-x` this past week.

Cheers 😄
