### ISSUE TITLE
Moon icon is not being displayed correctly on the first render

### ISSUE THREAD

**Issue by jorgeruvalcaba** [transitive-bullshit/nextjs-notion-starter-kit#68]
The first time the app loads, it doesn't display the moon icon correctly and throws this error:

```
react-dom.development.js?61bb:67 Warning: Prop `d` did not match. Server: "M256 48v48m0 320v48m147.08-355.08l-33.94 33.94M142.86 369.14l-33.94 33.94M464 256h-48m-320 0H48m355.08 147.08l-33.94-33.94M142.86 142.86l-33.94-33.94" Client: "M152.62 126.77c0-33 4.85-66.35 17.23-94.77C87.54 67.83 32 151.89 32 247.38 32 375.85 136.15 480 264.62 480c95.49 0 179.55-55.54 215.38-137.85-28.42 12.38-61.8 17.23-94.77 17.23-128.47 0-232.61-104.14-232.61-232.61z"
    at path
    at svg
    at IconBase
    at IoMoonSharp
    at a
    at div
    at footer
    at Footer (webpack-internal:///./components/Footer.tsx:27:25)
    at div
    at div
    at div
    at Block (webpack-internal:///./node_modules/react-notion-x/build/esm/block.js:44:81)
    at NotionBlockRenderer (webpack-internal:///./node_modules/react-notion-x/build/esm/renderer.js:47:17)
    at NotionContextProvider (webpack-internal:///./node_modules/react-notion-x/build/esm/context.js:80:17)
    at NotionRenderer (webpack-internal:///./node_modules/react-notion-x/build/esm/renderer.js:35:25)
    at NotionPage (webpack-internal:///./components/NotionPage.tsx:149:19)
    at NotionDomainPage
    at App (webpack-internal:///./pages/_app.tsx:84:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:149:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:637:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:768:24)
```

This is a project example with this issue: https://personal-site-v3.vercel.app/

**Comment by transitive-bullshit** [comment]
Yep; this is definitely a bug. I think it's https://github.com/react-icons/react-icons not playing nicely with Next.js + React hydration. See this article for more details https://www.joshwcomeau.com/react/the-perils-of-rehydration/
