### ISSUE TITLE
On npm run dev: HTTPError: Response Code 400 (bad request)

### ISSUE THREAD

**Issue by fynnay** [transitive-bullshit/nextjs-notion-starter-kit#77]
A while ago I set up [this test site](https://notion-hp.vercel.app/), which works just great both local dev and the deployed version (and thank you for that ❤️ ). Then I didn't touch it for a while.

Now, when I try to run `npm run dev` locally I'm getting this error:

![image](https://user-images.githubusercontent.com/14281431/111917164-c32dc080-8a7e-11eb-9f5f-1ac1387638ec.png)

In the console it shows this:

```prolog
page error notion-hp.vercel.app HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (C:\Users\fynn\Documents\Development\github\notion-hp\node_modules\got\dist\source\as-promise\index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1616352623783,
    socket: 1616352623784,
    lookup: 1616352623784,
    connect: 1616352623796,
    secureConnect: 1616352623814,
    upload: 1616352623814,
    response: 1616352624020,
    end: 1616352624022,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 12,
      tls: 18,
      request: 0,
      firstByte: 206,
      download: 2,
      total: 239
    }
  }
}
```

This is my repo: https://github.com/fynnay/notion-hp

I'm sure I'm missing something obvious but being very new to react and next I have no Idea where to start looking. I'd greatly appreciate any help.

**Comment by fynnay** [comment]
Solved. Installed updated _dependencies_

Here are my steps:

- `git remote add upstream https://github.com/transitive-bullshit/nextjs-notion-starter-kit`
- `git pull upstream main`
- `npm install`
- `npm run dev` 👏 🎉
