### ISSUE TITLE
Build process warning messages.

### ISSUE THREAD

**Issue by chof64** [transitive-bullshit/nextjs-notion-starter-kit#84]
I tried these steps and it is working fine. But during the build process, I saw lots of warning, but don't seem to affect the build output.

```15:01:47.943  	Cloning github.com/chof64/error404-notion-site (Branch: main, Commit: 3bde9db)
15:01:48.487  	Cloning completed in 544ms
15:01:48.491  	Analyzing source code...
15:01:49.048  	Installing build runtime...
15:01:49.809  	Build runtime installed: 760.024ms
15:01:50.584  	Installing build runtime...
15:01:51.374  	Build runtime installed: 790.738ms
15:01:52.164  	Installing build runtime...
15:01:52.929  	Build runtime installed: 764.474ms
15:01:53.707  	Installing build runtime...
15:01:54.347  	Build runtime installed: 639.778ms
15:01:55.150  	Installing build runtime...
15:01:55.886  	Build runtime installed: 735.999ms
15:01:56.666  	Installing build runtime...
15:01:57.407  	Build runtime installed: 740.276ms
15:01:58.152  	Installing build runtime...
15:02:01.241  	Build runtime installed: 3088.170ms
15:02:05.134  	Looking up build cache...
15:02:05.457  	Looking up build cache...
15:02:05.466  	Looking up build cache...
15:02:05.530  	Looking up build cache...
15:02:05.627  	Looking up build cache...
15:02:05.663  	Build cache found. Downloading...
15:02:05.836  	Build cache found. Downloading...
15:02:05.845  	Build cache found. Downloading...
15:02:05.904  	Build cache found. Downloading...
15:02:06.062  	Build cache found. Downloading...
15:02:35.036  	Build cache downloaded [213.68 MB]: 29129.883ms
15:02:36.325  	Warning: Due to "engines": { "node": ">=10" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
15:02:36.332  	Installing dependencies...
15:02:36.787  	Build cache downloaded [213.68 MB]: 31120.867ms
15:02:36.961  	Build cache downloaded [213.68 MB]: 31114.556ms
15:02:37.171  	Build cache downloaded [213.68 MB]: 31107.665ms
15:02:37.531  	Build cache downloaded [213.68 MB]: 31693.647ms
15:02:37.596  	yarn install v1.22.10
15:02:37.682  	info No lockfile found.
15:02:37.707  	[1/5] Validating package.json...
15:02:37.712  	[2/5] Resolving packages...
15:02:39.093  	Warning: Due to "engines": { "node": ">=10" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
15:02:39.097  	Installing dependencies...
15:02:39.254  	Warning: Due to "engines": { "node": ">=10" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
15:02:39.258  	Installing dependencies...
15:02:39.473  	Warning: Due to "engines": { "node": ">=10" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
15:02:39.480  	Installing dependencies...
15:02:39.489  	Warning: Due to "engines": { "node": ">=10" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
15:02:39.506  	Installing dependencies...
15:02:42.324  	warning puppeteer-social-image-transitive-bs > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
15:02:42.342  	warning puppeteer-social-image-transitive-bs > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
15:02:44.538  	warning static-tweets > cheerio > cheerio-select-tmp@0.1.1: Use cheerio-select instead
15:02:47.935  	warning babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
15:02:48.959  	[3/5] Fetching packages...
15:03:18.883  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
15:03:18.883  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
15:03:18.891  	[4/5] Linking dependencies...
15:03:18.893  	warning " > dangerously-set-html-content@1.0.8" has unmet peer dependency "prop-types@^15.5.4".
15:03:18.894  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
15:03:18.894  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
15:03:18.895  	warning " > puppeteer-social-image-transitive-bs@0.8.2" has incorrect peer dependency "puppeteer@^2".
15:03:18.896  	warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
15:03:18.897  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
15:03:18.897  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
15:03:18.897  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
15:03:18.897  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
15:03:18.898  	warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:03:18.898  	warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:03:18.898  	warning " > react-static-tweets@0.2.6" has unmet peer dependency "date-fns@>=2".
15:03:18.899  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "@types/node-fetch@2".
15:03:18.899  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "node-fetch@2".
15:03:18.899  	warning "static-tweets > @vercel/fetch > @vercel/fetch-retry@5.0.3" has unmet peer dependency "node-fetch@*".
15:03:18.899  	warning "static-tweets > @vercel/fetch > @vercel/fetch-cached-dns@2.0.1" has unmet peer dependency "node-fetch@*".
15:03:18.899  	warning " > use-dark-mode@2.3.1" has incorrect peer dependency "react@^16.8.0".
15:03:18.900  	warning "use-dark-mode > @use-it/event-listener@0.1.6" has incorrect peer dependency "react@^16.8.0".
15:03:31.359  	[5/5] Building fresh packages...
15:03:33.030  	success Saved lockfile.
15:03:33.036  	Done in 55.45s.
15:03:33.446  	yarn install v1.22.10
15:03:33.516  	Using TypeScript 4.2.3 (local user-provided)
15:03:33.532  	info No lockfile found.
15:03:33.552  	[1/5] Validating package.json...
15:03:33.560  	[2/5] Resolving packages...
15:03:37.089  	warning puppeteer-social-image-transitive-bs > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
15:03:37.113  	warning puppeteer-social-image-transitive-bs > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
15:03:39.117  	warning static-tweets > cheerio > cheerio-select-tmp@0.1.1: Use cheerio-select instead
15:03:40.715  	warning babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
15:03:42.371  	[3/5] Fetching packages...
15:03:43.293  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
15:03:43.294  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
15:03:43.310  	[4/5] Linking dependencies...
15:03:43.313  	warning " > dangerously-set-html-content@1.0.8" has unmet peer dependency "prop-types@^15.5.4".
15:03:43.314  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
15:03:43.314  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
15:03:43.316  	warning " > puppeteer-social-image-transitive-bs@0.8.2" has incorrect peer dependency "puppeteer@^2".
15:03:43.317  	warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
15:03:43.318  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
15:03:43.318  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
15:03:43.319  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
15:03:43.319  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
15:03:43.321  	warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:03:43.321  	warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:03:43.322  	warning " > react-static-tweets@0.2.6" has unmet peer dependency "date-fns@>=2".
15:03:43.323  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "@types/node-fetch@2".
15:03:43.323  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "node-fetch@2".
15:03:43.324  	warning "static-tweets > @vercel/fetch > @vercel/fetch-retry@5.0.3" has unmet peer dependency "node-fetch@*".
15:03:43.324  	warning "static-tweets > @vercel/fetch > @vercel/fetch-cached-dns@2.0.1" has unmet peer dependency "node-fetch@*".
15:03:43.324  	warning " > use-dark-mode@2.3.1" has incorrect peer dependency "react@^16.8.0".
15:03:43.324  	warning "use-dark-mode > @use-it/event-listener@0.1.6" has incorrect peer dependency "react@^16.8.0".
15:03:53.143  	Uploading build outputs...
15:03:53.727  	Deploying build outputs...
15:03:56.369  	[5/5] Building fresh packages...
15:03:58.141  	success Saved lockfile.
15:03:58.147  	Done in 24.71s.
15:03:58.412  	yarn install v1.22.10
15:03:58.472  	info No lockfile found.
15:03:58.483  	[1/5] Validating package.json...
15:03:58.492  	[2/5] Resolving packages...
15:03:58.529  	Using TypeScript 4.2.3 (local user-provided)
15:04:00.246  	Warning: Due to "engines": { "node": ">=10" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
15:04:00.251  	Installing dependencies...
15:04:02.720  	warning puppeteer-social-image-transitive-bs > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
15:04:02.753  	warning puppeteer-social-image-transitive-bs > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
15:04:04.997  	warning static-tweets > cheerio > cheerio-select-tmp@0.1.1: Use cheerio-select instead
15:04:05.972  	Uploading build outputs...
15:04:06.033  	Deploying build outputs...
15:04:07.233  	warning babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
15:04:07.853  	Done with "api/robots.txt.ts"
15:04:08.251  	[3/5] Fetching packages...
15:04:09.177  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
15:04:09.177  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
15:04:09.187  	[4/5] Linking dependencies...
15:04:09.190  	warning " > dangerously-set-html-content@1.0.8" has unmet peer dependency "prop-types@^15.5.4".
15:04:09.190  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
15:04:09.190  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
15:04:09.192  	warning " > puppeteer-social-image-transitive-bs@0.8.2" has incorrect peer dependency "puppeteer@^2".
15:04:09.193  	warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
15:04:09.194  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
15:04:09.194  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
15:04:09.195  	warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:04:09.196  	warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:04:09.196  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
15:04:09.196  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
15:04:09.197  	warning " > react-static-tweets@0.2.6" has unmet peer dependency "date-fns@>=2".
15:04:09.201  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "@types/node-fetch@2".
15:04:09.202  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "node-fetch@2".
15:04:09.202  	warning "static-tweets > @vercel/fetch > @vercel/fetch-cached-dns@2.0.1" has unmet peer dependency "node-fetch@*".
15:04:09.202  	warning "static-tweets > @vercel/fetch > @vercel/fetch-retry@5.0.3" has unmet peer dependency "node-fetch@*".
15:04:09.202  	warning " > use-dark-mode@2.3.1" has incorrect peer dependency "react@^16.8.0".
15:04:09.202  	warning "use-dark-mode > @use-it/event-listener@0.1.6" has incorrect peer dependency "react@^16.8.0".
15:04:10.330  	Looking up build cache...
15:04:10.754  	Build cache found. Downloading...
15:04:23.069  	[5/5] Building fresh packages...
15:04:25.261  	Build cache downloaded [217.32 MB]: 14504.539ms
15:04:25.369  	success Saved lockfile.
15:04:25.375  	Done in 26.97s.
15:04:25.801  	yarn install v1.22.10
15:04:25.858  	Using TypeScript 4.2.3 (local user-provided)
15:04:25.891  	info No lockfile found.
15:04:25.906  	[1/5] Validating package.json...
15:04:25.911  	[2/5] Resolving packages...
15:04:26.776  	Warning: Due to "engines": { "node": ">=10" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
15:04:26.796  	Installing dependencies...
15:04:29.440  	warning puppeteer-social-image-transitive-bs > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
15:04:29.468  	warning puppeteer-social-image-transitive-bs > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
15:04:30.657  	warning static-tweets > cheerio > cheerio-select-tmp@0.1.1: Use cheerio-select instead
15:04:33.714  	warning babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
15:04:34.814  	[3/5] Fetching packages...
15:04:35.720  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
15:04:35.720  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
15:04:35.731  	[4/5] Linking dependencies...
15:04:35.733  	warning " > dangerously-set-html-content@1.0.8" has unmet peer dependency "prop-types@^15.5.4".
15:04:35.733  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
15:04:35.734  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
15:04:35.735  	warning " > puppeteer-social-image-transitive-bs@0.8.2" has incorrect peer dependency "puppeteer@^2".
15:04:35.736  	warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
15:04:35.737  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
15:04:35.737  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
15:04:35.737  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
15:04:35.738  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
15:04:35.739  	warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:04:35.739  	warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:04:35.740  	warning " > react-static-tweets@0.2.6" has unmet peer dependency "date-fns@>=2".
15:04:35.740  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "@types/node-fetch@2".
15:04:35.741  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "node-fetch@2".
15:04:35.741  	warning "static-tweets > @vercel/fetch > @vercel/fetch-retry@5.0.3" has unmet peer dependency "node-fetch@*".
15:04:35.741  	warning "static-tweets > @vercel/fetch > @vercel/fetch-cached-dns@2.0.1" has unmet peer dependency "node-fetch@*".
15:04:35.741  	warning " > use-dark-mode@2.3.1" has incorrect peer dependency "react@^16.8.0".
15:04:35.742  	warning "use-dark-mode > @use-it/event-listener@0.1.6" has incorrect peer dependency "react@^16.8.0".
15:04:37.847  	Uploading build outputs...
15:04:37.943  	Deploying build outputs...
15:04:40.113  	Done with "api/get-tweet-ast/[tweetId].ts"
15:04:47.078  	[5/5] Building fresh packages...
15:04:49.445  	success Saved lockfile.
15:04:49.451  	Done in 23.66s.
15:04:49.829  	yarn install v1.22.10
15:04:49.839  	Using TypeScript 4.2.3 (local user-provided)
15:04:50.088  	[1/5] Validating package.json...
15:04:50.092  	[2/5] Resolving packages...
15:04:50.839  	success Already up-to-date.
15:04:50.847  	Done in 1.03s.
15:04:51.292  	Using TypeScript 4.2.3 (local user-provided)
15:04:51.351  	yarn install v1.22.10
15:04:51.718  	[1/5] Validating package.json...
15:04:51.723  	[2/5] Resolving packages...
15:04:52.845  	[3/5] Fetching packages...
15:04:54.430  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
15:04:54.430  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
15:04:54.477  	[4/5] Linking dependencies...
15:04:54.482  	warning " > dangerously-set-html-content@1.0.8" has unmet peer dependency "prop-types@^15.5.4".
15:04:54.483  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
15:04:54.484  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
15:04:54.488  	warning " > puppeteer-social-image-transitive-bs@0.8.2" has incorrect peer dependency "puppeteer@^2".
15:04:54.490  	warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
15:04:54.491  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
15:04:54.492  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
15:04:54.493  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
15:04:54.494  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
15:04:54.496  	warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:04:54.497  	warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:04:54.498  	warning " > react-static-tweets@0.2.6" has unmet peer dependency "date-fns@>=2".
15:04:54.501  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "@types/node-fetch@2".
15:04:54.501  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "node-fetch@2".
15:04:54.501  	warning "static-tweets > @vercel/fetch > @vercel/fetch-cached-dns@2.0.1" has unmet peer dependency "node-fetch@*".
15:04:54.502  	warning "static-tweets > @vercel/fetch > @vercel/fetch-retry@5.0.3" has unmet peer dependency "node-fetch@*".
15:04:54.503  	warning " > use-dark-mode@2.3.1" has incorrect peer dependency "react@^16.8.0".
15:04:54.503  	warning "use-dark-mode > @use-it/event-listener@0.1.6" has incorrect peer dependency "react@^16.8.0".
15:05:16.224  	[5/5] Building fresh packages...
15:05:19.363  	Done in 28.02s.
15:05:19.398  	Detected Next.js version: 10.1.3
15:05:19.402  	Running "yarn run build"
15:05:19.905  	yarn install v1.22.10
15:05:20.008  	info No lockfile found.
15:05:20.025  	[1/5] Validating package.json...
15:05:20.030  	[2/5] Resolving packages...
15:05:20.194  	yarn run v1.22.10
15:05:20.308  	$ next build
15:05:21.540  	Uploading build outputs...
15:05:21.700  	Deploying build outputs...
15:05:22.045  	Uploading build outputs...
15:05:22.165  	Deploying build outputs...
15:05:22.372  	info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
15:05:22.740  	info  - Checking validity of types...
15:05:23.383  	warning puppeteer-social-image-transitive-bs > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
15:05:23.405  	warning puppeteer-social-image-transitive-bs > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
15:05:23.815  	Done with "api/search-notion.ts"
15:05:24.162  	warning static-tweets > cheerio > cheerio-select-tmp@0.1.1: Use cheerio-select instead
15:05:24.451  	Done with "api/sitemap.xml.ts"
15:05:26.000  	warning babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
15:05:27.160  	[3/5] Fetching packages...
15:05:28.301  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
15:05:28.302  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
15:05:28.316  	[4/5] Linking dependencies...
15:05:28.318  	warning " > dangerously-set-html-content@1.0.8" has unmet peer dependency "prop-types@^15.5.4".
15:05:28.319  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
15:05:28.319  	warning " > dangerously-set-html-content@1.0.8" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
15:05:28.321  	warning " > puppeteer-social-image-transitive-bs@0.8.2" has incorrect peer dependency "puppeteer@^2".
15:05:28.322  	warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
15:05:28.322  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
15:05:28.322  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
15:05:28.323  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
15:05:28.323  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
15:05:28.324  	warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:05:28.325  	warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
15:05:28.325  	warning " > react-static-tweets@0.2.6" has unmet peer dependency "date-fns@>=2".
15:05:28.326  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "@types/node-fetch@2".
15:05:28.326  	warning "static-tweets > @vercel/fetch@6.1.0" has unmet peer dependency "node-fetch@2".
15:05:28.326  	warning "static-tweets > @vercel/fetch > @vercel/fetch-retry@5.0.3" has unmet peer dependency "node-fetch@*".
15:05:28.326  	warning "static-tweets > @vercel/fetch > @vercel/fetch-cached-dns@2.0.1" has unmet peer dependency "node-fetch@*".
15:05:28.327  	warning " > use-dark-mode@2.3.1" has incorrect peer dependency "react@^16.8.0".
15:05:28.327  	warning "use-dark-mode > @use-it/event-listener@0.1.6" has incorrect peer dependency "react@^16.8.0".
15:05:30.690  	info  - Creating an optimized production build...
15:05:42.310  	[5/5] Building fresh packages...
15:05:44.594  	success Saved lockfile.
15:05:44.601  	Done in 24.71s.
15:05:45.022  	Using TypeScript 4.2.3 (local user-provided)
15:05:58.794  	info  - Compiled successfully
15:05:58.795  	info  - Collecting page data...
15:05:59.230  	> Build error occurred
15:05:59.234  	Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /vercel/workpath3/node_modules/react-notion-x/build/cjs/index.js
15:05:59.234  	require() of ES modules is not supported.
15:05:59.234  	require() of /vercel/workpath3/node_modules/react-notion-x/build/cjs/index.js from /vercel/workpath3/.next/server/pages/_error.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
15:05:59.234  	Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /vercel/workpath3/node_modules/react-notion-x/package.json.
15:05:59.235  	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
15:05:59.235  	    at Module.load (internal/modules/cjs/loader.js:928:32)
15:05:59.235  	    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
15:05:59.235  	    at Module.require (internal/modules/cjs/loader.js:952:19)
15:05:59.235  	    at require (internal/modules/cjs/helpers.js:88:18)
15:05:59.236  	    at Object.R1xE (/vercel/workpath3/.next/server/pages/_error.js:1151:18)
15:05:59.236  	    at __webpack_require__ (/vercel/workpath3/.next/server/pages/_error.js:23:31)
15:05:59.236  	    at Object.bgFo (/vercel/workpath3/.next/server/pages/_error.js:1447:32)
15:05:59.236  	    at __webpack_require__ (/vercel/workpath3/.next/server/pages/_error.js:23:31)
15:05:59.236  	    at Module.D4/9 (/vercel/workpath3/.next/server/pages/_error.js:578:68)
15:05:59.236  	    at __webpack_require__ (/vercel/workpath3/.next/server/pages/_error.js:23:31)
15:05:59.237  	    at Object.4 (/vercel/workpath3/.next/server/pages/_error.js:288:18)
15:05:59.237  	    at __webpack_require__ (/vercel/workpath3/.next/server/pages/_error.js:23:31)
15:05:59.237  	    at /vercel/workpath3/.next/server/pages/_error.js:91:18
15:05:59.237  	    at Object.<anonymous> (/vercel/workpath3/.next/server/pages/_error.js:94:10)
15:05:59.237  	    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
15:05:59.238  	  code: 'ERR_REQUIRE_ESM'
15:05:59.238  	}
15:05:59.324  	error Command failed with exit code 1.
15:05:59.325  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
15:05:59.346  	Error: Command "yarn run build" exited with 1
15:06:11.277  	Uploading build outputs...
15:06:12.246  	Deploying build outputs...
15:06:15.482  	Done with "api/render-social-image/[pageId].ts"
15:06:18.359  	Build completed. Populating build cache...
15:07:03.114  	Uploading build cache [213.68 MB]...
15:07:12.493  	Build cache uploaded: 9379.284ms
15:07:12.738  	Done with "api/create-preview-image.ts"
15:07:13.483  	Done with "package.json"```

Which actually resurlted in some sort of error.

**Comment by transitive-bullshit** [comment]
Thanks @chof64; 95% of these are warnings that can be safely ignored.

This one was introduced recently and I need to fix.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /vercel/workpath3/node_modules/react-notion-x/build/cjs/index.js
15:05:59.234  	require() of ES modules is not supported.
15:05:59.234  	require() of /vercel/workpath3/node_modules/react-notion-x/build/cjs/index.js from /vercel/workpath3/.next/server/pages/_error.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
15:05:59.234  	Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /vercel/workpath3/node_modules/react-notion-x/package.json.
```

**Comment by transitive-bullshit** [comment]
This should now be fixed. There will always be some packager warnings since third-party packages don't always have peer dependency constraints set up correctly (like depending on react 16 explicitly whereas react 17 works fine as well).

Please let me know if you run into any additional issues.

**Comment by chof64** [comment]
Thank you @transitive-bullshit. I will try and update.
